registrator:  
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

registrator-kv:
  command: -ip 192.168.99.99  consulkv://consul:8500/services
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

consul:
  image: "progrium/consul:latest"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53"
  command: "-server -bootstrap -ui-dir /ui"
  restart: always

Cadvisor:
  image: google/cadvisor
  ports:
    - "9999:8080"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  restart: always

