- hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml

  vars:
    - container_image: peterbourgon/tns-app
    - container_name: ssv4
    - http_address: /
  roles:
    - service
