---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml
  vars:
    - container_image: peterbourgon/tns-app
    - container_name: ssv4
    - http_address: /
  roles:
    - server
    - docker
    - compose
    - consul
    - git
    - haproxy
    - service
